import('./defaults.rb')
import('./android.rb')
import('./ios.rb')
import('./utils.rb')
import('./tools/codesign.rb')
import('./tools/hermes.rb')

before_all do |lane, options|

  Dir.chdir('../')
  
  sh(
    log: verbose_logging_enabled(),
    command: [
      'mkdir -p',
      './build/android',
      './build/intermediates',
    ].join(' ')
  )

  Dotenv.overload('.env')

end

after_all do |lane, options|

  sh(
    log: verbose_logging_enabled(),
    command: [
      'rm -rf',
      './build/intermediates',
      './build/tsc-out',
      './fastlane/report.xml',
    ].join(" ")
  )

end

desc "Builds native apps and stores them in the `./build` folder"
desc "Parameters:"
desc "- env - environment to use. This will switch local environment and replace .env file with one from ./env dir. **Defaults to what is in current .env file**"
desc "- build_number - build number"
desc "Output:"
desc "The result of the command is a `./build/android` folder in the project root containing build artifacts:"
desc "- .apk or .aab"
desc "- source maps"
lane :native do |options|

  proxy_sh('android native', options)
  proxy_sh('ios native', options)

end
