name: Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.vscode'
      - '.husky'
      - '.jest/**'
      - '.eslint*'
      - '.gitignore'
      - '.jest.config.js'
      - '**.md'
      - '**.spec'
      - 'tsconfig*'

  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: 'Environment to build. See https://github.com/artyorsh/rnapp/settings/environments.'

env:
  RNAPP_ENV_NAME: ${{ vars.RNAPP_ENV_NAME }}
  RNAPP_APP_ID: ${{ vars.RNAPP_APP_ID }}
  RNAPP_GRAFANA_HOST: ${{ vars.RNAPP_GRAFANA_HOST }}
  RNAPP_AUTH_TOKEN_REFRESH_THRESHOLD_MINUTES: ${{ vars.RNAPP_AUTH_TOKEN_REFRESH_THRESHOLD_MINUTES }}
  RNAPP_STORAGE_ENCRYPTION_KEY: ${{ secrets.RNAPP_STORAGE_ENCRYPTION_KEY }}

jobs:

  build:
    runs-on: macos-15

    strategy:
      matrix:
        platform: [android]

    environment: ${{ inputs.environment || 'staging' }}

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/workflows/actions/prepare

      - name: Create .env file
        run: |
          # Only export environment variables with "RNAPP_" prefix
          env | grep '^RNAPP_' > ${{ github.workspace }}/.env

      - name: Checkout codesign repository
        uses: actions/checkout@v4
        with:
          repository: artyorsh/rnapp-codesign
          token: ${{ secrets.CODESIGN_REPO_TOKEN }}
          path: codesign

      - name: Trigger native build
        run:
          echo "Building for ${{ matrix.platform }} in environment ${{ inputs.environment || 'staging' }}"

      - name: Archive results
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.platform }}
          path: build/${{ matrix.platform }}
          retention-days: 1
