name: Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.vscode'
      - '.husky'
      - '.jest/**'
      - '.eslint*'
      - '.gitignore'
      - '.jest.config.js'
      - '**.md'
      - '**.spec'
      - 'tsconfig*'

  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: 'Environment to build. See https://github.com/artyorsh/rnapp/settings/environments.'

env:
  RNAPP_ENV_NAME: ${{ vars.RNAPP_ENV_NAME }}
  RNAPP_APP_ID: ${{ vars.RNAPP_APP_ID }}
  RNAPP_GRAFANA_HOST: ${{ vars.RNAPP_GRAFANA_HOST }}
  RNAPP_AUTH_TOKEN_REFRESH_THRESHOLD_MINUTES: ${{ vars.RNAPP_AUTH_TOKEN_REFRESH_THRESHOLD_MINUTES }}
  RNAPP_STORAGE_ENCRYPTION_KEY: ${{ secrets.RNAPP_STORAGE_ENCRYPTION_KEY }}
  FASTLANE_BUILD_SCHEME: ${{ vars.FASTLANE_BUILD_SCHEME }}
  FASTLANE_BUILD_TYPE: ${{ vars.FASTLANE_BUILD_TYPE }}
  FASTLANE_ANDROID_BUILD_TASK: ${{ vars.FASTLANE_ANDROID_BUILD_TASK }}
  FASTLANE_ANDROID_KEYSTORE_FILE: ${{ github.workspace }}/codesign/${{ vars.FASTLANE_ANDROID_KEYSTORE_FILE }}
  FASTLANE_ANDROID_KEYSTORE_PASSWORD: ${{ secrets.FASTLANE_ANDROID_KEYSTORE_PASSWORD }}
  FASTLANE_ANDROID_KEYSTORE_KEY_ALIAS: ${{ secrets.FASTLANE_ANDROID_KEYSTORE_KEY_ALIAS }}
  FASTLANE_ANDROID_KEYSTORE_KEY_PASSWORD: ${{ secrets.FASTLANE_ANDROID_KEYSTORE_KEY_PASSWORD }}
  FASTLANE_IOS_EXPORT_METHOD: ${{ vars.FASTLANE_IOS_EXPORT_METHOD }}
  FASTLANE_IOS_TEAM_ID: ${{ secrets.FASTLANE_IOS_TEAM_ID }}
  FASTLANE_CI_LOG_LEVEL: ${{ vars.FASTLANE_CI_LOG_LEVEL }}
  FASTLANE_IOS_CERT_PATH: ${{ github.workspace }}/codesign/${{ vars.FASTLANE_IOS_CERT_PATH }}
  FASTLANE_IOS_CERT_PASSWORD: ${{ secrets.FASTLANE_IOS_CERT_PASSWORD }}
  FASTLANE_IOS_PROVISIONING_PROFILE_PATH: ${{ github.workspace }}/codesign/${{ vars.FASTLANE_IOS_PROVISIONING_PROFILE_PATH }}

jobs:

  build:
    runs-on: macos-15
    environment: ${{ inputs.environment || 'staging' }}

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/workflows/actions/prepare

      - name: Debug keychains
        run: security list-keychains

      - name: Create .env file
        run: |
          # Only export environment variables with "RNAPP_" prefix
          env | grep '^RNAPP_' > ${{ github.workspace }}/.env

      - name: Checkout codesign repository
        uses: actions/checkout@v4
        with:
          repository: artyorsh/rnapp-codesign
          token: ${{ secrets.CODESIGN_REPO_TOKEN }}
          path: codesign

      - name: Trigger native build (android)
        run:
          bundle exec fastlane ios native

      - name: Archive results
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build
          retention-days: 1
