name: Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.vscode'
      - '.husky'
      - '.jest/**'
      - '.eslint*'
      - '.gitignore'
      - '.jest.config.js'
      - '**.md'
      - '**.spec'
      - 'tsconfig*'

env:
  RNAPP_ENV_NAME: ${{ vars.RNAPP_ENV_NAME }}
  RNAPP_APP_ID: ${{ vars.RNAPP_APP_ID }}
  RNAPP_GRAFANA_HOST: ${{ vars.RNAPP_GRAFANA_HOST }}
  RNAPP_BUILD_SCHEME: ${{ vars.RNAPP_BUILD_SCHEME }}
  RNAPP_BUILD_TYPE: ${{ vars.RNAPP_BUILD_TYPE }}
  RNAPP_ANDROID_BUILD_TASK: ${{ vars.RNAPP_ANDROID_BUILD_TASK }}
  RNAPP_ANDROID_KEYSTORE_FILE: ${{ github.workspace }}/codesign/${{ vars.RNAPP_ANDROID_KEYSTORE_FILE }}
  RNAPP_ANDROID_KEYSTORE_PASSWORD: ${{ secrets.RNAPP_ANDROID_KEYSTORE_PASSWORD }}
  RNAPP_ANDROID_KEYSTORE_KEY_ALIAS: ${{ secrets.RNAPP_ANDROID_KEYSTORE_KEY_ALIAS }}
  RNAPP_ANDROID_KEYSTORE_KEY_PASSWORD: ${{ secrets.RNAPP_ANDROID_KEYSTORE_KEY_PASSWORD }}
  RNAPP_IOS_EXPORT_METHOD: ${{ vars.RNAPP_IOS_EXPORT_METHOD }}
  RNAPP_CI_LOG_LEVEL: ${{ vars.RNAPP_CI_LOG_LEVEL }}

jobs:

  build:
    runs-on: macos-latest
    environment: staging

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/workflows/actions/prepare

      - name: Create .env file
        run: |
          # Only export environment variables with "RNAPP_" prefix
          env | grep '^RNAPP_' > .env

      - name: Checkout codesign repository
        uses: actions/checkout@v4
        with:
          repository: artyorsh/rnapp-codesign
          path: codesign

      - name: Trigger native build (android)
        run: bundle exec fastlane android native

      - name: Archive results
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build
          retention-days: 1
