name: Build

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: 'Environment to build. See https://github.com/artyorsh/rnapp/settings/environments.'

env:
  EXPO_EAS_VERSION: latest

jobs:

  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    environment: ${{ inputs.environment || 'preview' }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - uses: expo/expo-github-action@v8
        with:
          eas-version: ${{ env.EXPO_EAS_VERSION }}
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install node modules
        run: yarn

      - name: Trigger EAS build
        run: eas build --non-interactive
